# 锚点定义:
dim: &exploration_dim_ 2
init_x_: &init_x_ 0.0
init_y_: &init_y_ 0.0
init_z_: &init_z_ 1.0


# 变量:
Preprocess:
  perception_dim: *exploration_dim_ 

GridMap2D:
  frame_id: world
  init_z: *init_z_
  grid_size: 0.2
  map_size: 20.0

Roadmap:
  frame_id: world
  init_x: *init_x_
  init_y: *init_y_
  init_z: *init_z_
  sample_dist_h: 0.5
  sample_dist_v: 0.5
  min_interval_h: 0.8
  min_interval_v: 0.8
  bound_margin_h: 1.0
  bound_margin_v: 1.0
  connectable_range: 3
  connectable_num: 5
  points_dist_to_occupied: 1.0
  points_dist_to_unknown: 1.0

ViewpointManager:
  frame_id: world
  init_z: *init_z_
  sample_dist_horizon: 0.5
  sample_dist_vertical: 0.5
  points_dist_thre_horizon: 1.5   # 新点和旧点的最小距离
  points_dist_thre_vertical: 1.5     # 新点和旧点的最小距离
  points_clear_dist_thre_horizon: 1.0
  points_clear_dist_thre_vertical: 1.0
  bound_margin_horizon: 1.0
  bound_margin_vertical: 1.0
  viewpoint_gain_thre: 2.0
  frontier_viewpoint_dist_thre: 4.0
  points_dist_to_occupied: 1.0
  points_dist_to_unknown: 1.0

RapidCoverPlanner:
  init_x: *init_x_
  init_y: *init_y_
  init_z: *init_z_
  planner_dim: *exploration_dim_
  stop_x_thre: 1.0
  stop_y_thre: 1.0
  stop_z_thre: 0.5 
  max_tour_point_num: 10
  viewpoint_ignore_thre: 0.5
  local_range: 8.0
  frontier_gain: 100.0
  tourpoint_ignore_thre: 0.8
  tourpoint_ignore_distance: 3.0
  is_directory: true
  alpha: 0.3
  lambda: 1.0
  