# 锚点定义:
dim: &exploration_dim_ 3
init_x_: &init_x_ 4.0
init_y_: &init_y_ 50.0
init_z_: &init_z_ 30.0


# 变量:
Preprocess:
  perception_dim: *exploration_dim_ 

GridMap3D:
  frame_id: world
  init_z: *init_z_
  grid_size: 0.5
  map_size_x: 40
  map_size_y: 40
  map_size_z: 40

Roadmap:
  frame_id: world
  init_x: *init_x_
  init_y: *init_y_
  init_z: *init_z_
  sample_dist_h: 1.0
  sample_dist_v: 1.0
  min_interval_h: 3.0
  min_interval_v: 2.0
  bound_margin_h: 1.0
  bound_margin_v: 1.0
  connectable_range: 6
  connectable_num: 6
  points_dist_to_occupied: 0.5
  points_dist_to_unknown: 0.5

ViewpointManager:
  frame_id: world
  init_z: *init_z_
  sample_dist_horizon: 1.0
  sample_dist_vertical: 1.0
  points_dist_thre_horizon: 2.0    # 新点和旧点的最小距离
  points_dist_thre_vertical: 3.0    # 新点和旧点的最小距离
  points_clear_dist_thre_horizon: 2.0
  points_clear_dist_thre_vertical: 2.0
  bound_margin_horizon: 1.0
  bound_margin_vertical: 1.0
  viewpoint_gain_thre: 2.0
  frontier_viewpoint_dist_thre: 5.0
  points_dist_to_occupied: 1.0
  points_dist_to_unknown: 1.0
  lower_fov: 10.0
  upper_fov: 30.0

RapidCoverPlanner:
  init_x: *init_x_
  init_y: *init_y_
  init_z: *init_z_
  planner_dim: *exploration_dim_
  stop_x_thre: 1.0
  stop_y_thre: 1.0
  stop_z_thre: 0.5 
  max_tour_point_num: 12
  viewpoint_ignore_thre: 1.0
  local_range: 15.0
  frontier_gain: 100.0
  tourpoint_ignore_thre: 1.0
  tourpoint_ignore_distance: 5.0
  is_directory: true
  alpha: 0.8
  lambda: 0.5
  