# 锚点定义:
dim: &exploration_dim_ 2
init_x_: &init_x_ 5.0
init_y_: &init_y_ 5.0
init_z_: &init_z_ 2.0


# 变量:
Preprocess:
  perception_dim: *exploration_dim_ 

GridMap2D:
  frame_id: world
  init_z: *init_z_
  grid_size: 0.4
  map_size: 29

Roadmap:
  frame_id: world
  init_x: *init_x_
  init_y: *init_y_
  init_z: *init_z_
  sample_dist_h: 1.0  # 水平采样间隔
  sample_dist_v: 1.0  # 垂直采样间隔
  min_interval_h: 2.0 # 图上水平点之间最小间隔
  min_interval_v: 2.0 # 图上竖直点之间最小间隔
  bound_margin_h: 1.0 # 水平上距离ESDF限制的box的边界的最小距离
  bound_margin_v: 1.0 # 竖直上距离ESDF限制的box的边界的最小距离
  connectable_range: 5
  connectable_num: 5
  points_dist_to_occupied: 0.5  # 有效点距离occupied的最小距离
  points_dist_to_unknown: 0.5   # 有效点距离unknown的最小距离

ViewpointManager:
  frame_id: world
  init_z: *init_z_
  sample_dist_horizon: 0.4
  sample_dist_vertical: 1.0
  points_dist_thre_horizon: 1.0      # 新点和旧点的最小距离
  points_dist_thre_vertical: 2.0     # 新点和旧点的最小距离
  points_clear_dist_thre_horizon: 0.8   # 水平消除目标点的距离:当机器人水平距离该点的距离<=该值,直接清除该点
  points_clear_dist_thre_vertical: 1.0  # 竖直消除目标点的距离:当机器人竖直距离该点的距离<=该值,直接清除该点
  bound_margin_horizon: 1.0
  bound_margin_vertical: 1.0
  viewpoint_gain_thre: 1.0
  frontier_viewpoint_dist_thre: 7.5 # frontier和viewpoint连线的最长距离
  points_dist_to_occupied: 1.5
  points_dist_to_unknown: 1.5

RapidCoverPlanner:
  init_x: *init_x_
  init_y: *init_y_
  init_z: *init_z_
  planner_dim: *exploration_dim_
  stop_x_thre: 1.0
  stop_y_thre: 1.0
  stop_z_thre: 0.5 
  max_tour_point_num: 15
  viewpoint_ignore_thre: 0.8
  local_range: 15.0
  frontier_gain: 100.0
  tourpoint_ignore_thre: 0.08
  tourpoint_ignore_distance: 3.0
  is_directory: true
  alpha: 0.3
  lambda: 0.7
  